In [135]:
import pandas as pd
import numpy as np

In [136]:
#df1=pd.read_csv('/content/Tamil_Movies.csv',usecols=['tittle','genre'])
#df1.head()

In [137]:
#df2=pd.read_csv('/content/Tamil_movies_dataset.csv',usecols=['MovieName','Genre'])
#df2.head()

In [138]:
#df2=df2.rename(columns={'MovieName':'tittle','Genre':'genre'})

In [139]:
#df2.columns

In [140]:
#df=pd.concat([df1, df2], ignore_index=True)

In [141]:
#df.shape

In [142]:
#df.isnull().sum()

In [143]:
#df.dropna(inplace=True)

In [144]:
#df['tittle'].value_counts()

In [145]:
#df['tittle']=df['tittle'].drop_duplicates()

In [146]:
#df['tittle'].value_counts()

In [147]:
#df.head()

In [245]:
df=pd.read_csv('Tamil_Movies.csv')
df.head()

,index,tittle,genre,overview,director,cast
0,0,I,Romance Thriller,The morale of the story is simply how pure lov...,Shankar S,"Vikram , Amy Jackson, Santhanam , Suresh Gopi,..."
1,1,Darling,Horror Comedy,A rather interesting plot about a group of you...,Sam Anton,"Gv Prakash, Karunas , Nikki Galrani, Rajendran..."
2,2,Aambala (U),Comedy Action,Long lost family members who have a grudge aga...,Sundar C,"Vishal Krishna, Hansika Motwani, Ramya Krishna..."
3,3,Isai (U/A),Love Drama,A maestro decides to snuff out his subordinate...,Suryah S.j.,"S J Surya, Savitri , Sathyaraj , Thambi Ramaia..."
4,4,Yennai Arindhaal,Action Drama,"The life of a young boy, Sathyadev, takes a de...",Gautham Menon,"Ajith Kumar, Anushka Shetty, Arun Vijay, Vivek..."

In [246]:
df.shapeusecols=['tittle','genre','overview','director']

C:\Users\DELL\AppData\Local\Temp\ipykernel_10656\4292138780.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.shapeusecols=['tittle','genre','overview','director']

In [247]:
#df['tag']=df['genre']+" "+df['overview']+" "+df['director']+" "+df['cast']

In [248]:
df['tag']=df['genre']+" "+df['overview']

In [249]:
df.drop(columns=['genre','overview','director','cast','index'],inplace=True)

In [250]:
df

                    tittle                                                tag
0                        I  Romance Thriller The morale of the story is si...
1                  Darling  Horror Comedy A rather interesting plot about ...
2              Aambala (U)  Comedy Action Long lost family members who hav...
3               Isai (U/A)  Love Drama A maestro decides to snuff out his ...
4         Yennai Arindhaal  Action Drama The life of a young boy, Sathyade...
..                     ...                                                ...
785  Thalaimai Seyalagam 2  Political Thriller A politician’s fight agains...
786          Raaja Paarvai  Drama A visually impaired man’s journey of res...
787           Koodal Nagar  Action Drama A man’s rise against local goons ...
788           Naan Rudhran  Action A man seeks justice for his family’s mu...
789         Thoongavanam 2  Action Thriller A cop’s mission to stop a drug...

[790 rows x 2 columns]

In [251]:
df=df.rename(columns={'tittle':'title'})#
df.drop(index=456, inplace=True)

In [252]:
df.shape

(789, 2)

In [253]:
df.isnull().sum()

title    0
tag      3
dtype: int64

In [254]:
df.dropna(inplace=True)

In [255]:
df['title'].value_counts()

title
Mersal                                4
Naane Varuvean                        3
Anbanavan Asaradhavan Adangadhavan    3
Thiruttu Payale 2                     3
Richie                                3
                                     ..
Maari 2                               1
Adanga Maru                           1
Kanaa                                 1
Seethakaathi                          1
Thoongavanam 2                        1
Name: count, Length: 718, dtype: int64

In [256]:
df['title']=df['title'].drop_duplicates()
#df.reset_index(drop=True, inplace=True)

In [257]:
df['title'].value_counts()

title
I                                    1
Good Night                           1
Oke Oka Jeevitham (Tamil Dub)        1
Krishna Vrinda Vihari (Tamil Dub)    1
Dongalunnaru Jagratha (Tamil Dub)    1
                                    ..
8 Thottakkal                         1
Kaatru Veliyidai                     1
Dora                                 1
Kavan                                1
Thoongavanam 2                       1
Name: count, Length: 718, dtype: int64

In [258]:
df.shape

(786, 2)

In [259]:
#from sentence_transformers import SentenceTransformer

In [220]:
#model=SentenceTransformer('all-MiniLM-L6-v2')

In [221]:
#embed=model.encode(df['tag'],show_progress_bar=True)

In [165]:
#cosine=cosine_similarity(embed)

In [166]:
'''
def recommend(tittle, n=5):
    idx = df[df['tittle'] == tittle].index[0]
    scores = list(enumerate(cosine[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    for i in scores[1:n+1]:
        print(df.iloc[i[0]]['tittle'])

'''

"\ndef recommend(tittle, n=5):\n    idx = df[df['tittle'] == tittle].index[0]\n    scores = list(enumerate(cosine[idx]))\n    scores = sorted(scores, key=lambda x: x[1], reverse=True)\n    for i in scores[1:n+1]:\n        print(df.iloc[i[0]]['tittle'])\n\n"

In [167]:
#recommend("Baahubali")

In [260]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [261]:
#cv=CountVectorizer(max_features=719,stop_words='english')

In [262]:
cv=TfidfVectorizer(max_features=5000,stop_words='english')

In [263]:
vector=cv.fit_transform(df['tag']).toarray()

In [264]:
vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [265]:
vector.shape

(786, 2147)

In [266]:
from sklearn.metrics.pairwise import cosine_similarity

In [267]:
cosine=cosine_similarity(vector)

In [268]:
i=df[df['title']=='Kaatteri'].index[0]
i

IndexError: index 0 is out of bounds for axis 0 with size 0

In [269]:
sorted(list(enumerate(cosine[i])),reverse=True,key=lambda vec:vec[1])[:5]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [270]:
distance=sorted(list(enumerate(cosine[i])),reverse=True,key=lambda vec:vec[1])
for i in distance[0:5]:
  print(df.iloc[i[0]].title)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [271]:
df.iloc[456]

title                                             Ayngaran
tag      Action Drama An inventor fights to protect his...
Name: 460, dtype: object

In [272]:
def recommend(movie):
    index = df[df['title'] == movie].index[0]
    distances = list(enumerate(cosine[index]))
    distances = sorted(distances, reverse=True, key=lambda x: x[1])
    
    for i in distances[1:6]:  
        print(df.iloc[i[0]].title)

In [281]:
recommend('Indru Netru Naalai')

uttama villain
100% Kadhal
Devi 2
Maya
Anbulla Ghilli

In [274]:
#  Romeo Juliet     Darling    Bigil  Kanchana 2    Master

In [ ]:
df['tittle'].unique()

array(['I', 'Darling', 'Aambala (U)', 'Isai (U/A)', 'Yennai Arindhaal',
       'Anegan', 'Tamiluku En Ondrai Aluthavum', 'Sandamarudham',
       'Kakki Sattai', 'Enakkul Oruvan', 'Rajathanthiram', 'Valiyavan',
       'Komban', 'Nanbenda', 'Sagaptham', 'Ok Kanmani', 'Kanchana 2',
       'Vai Raja Vai', 'uttama villain', 'India Pakistan',
       '36 Vayadhinile', 'Purampokku', 'Demonte Colony', 'Masss',
       'Kaaka Muttai', 'Romeo Juliet', 'Papanasam ', 'Baahubali',
       'Maalai Nerathu Mayakkam', 'Azhagu Kutti Chellam', 'Kathakali',
       'Rajini Murugan', 'Thaarai Thappattai', 'Irudhi Suttru',
       'Aranmanai 2', 'Visaranai', 'Vil Ambu', 'Anjala', 'Theri',
       'Kabali', '24', 'Iru Mugan', 'Joker', 'Dharma Durai', 'Miruthan',
       nan, 'Dhuruvangal Pathinaaru', 'Aandavan Kattalai',
       'Baahubali 2: The Conclusion', 'Mersal', 'Vivegam',
       'Theeran Adhigaaram Ondru', 'Vikram Vedha', '2', 'Kaala',
       'Thaanaa Serndha Koottam', 'Vada Chennai', 'Irumbu Thirai',
       'Kaithi', 'Petta', 'Viswasam', 'Mouna Guru', '7 Aum Arivu',
       'Vaagai Sooda Vaa', 'Mankatha', 'Kanchana: Muni 2',
       'Deiva Thirumagal', 'Vaanam', 'Ko', 'Payanam', 'Yutham Sei',
       'Aadukalam', 'Naduvula Konjam Pakkatha Kaanom', 'Thuppakki',
       'Pizza', 'Naan', 'The Fly', 'Kalakalappu', 'Vazhakku Enn 18/9',
       'Kumki', 'Neethaane En Ponvasantham', 'Thalaimuraigal', 'Biriyani',
       'Ivan Veramaathiri', 'Kalyana Samayal Saadham', 'Irandam Ulagam',
       'Pandiya Naadu', 'Arrambam', 'Onaayum Aattukkuttiyum', 'Raja Rani',
       '6 Candles', 'Moodar Koodam', 'Varuthapadatha Valibar Sangam',
       'Thanga Meengal', 'Aadhalal Kadhal Seiveer', 'Maryan', 'Singam 2',
       'Theeya Velai Seiyyanum Kumaru', 'Neram', 'Soodhu Kavvum',
       'Ethir Neechal', 'Kedi Billa Killadi Ranga', 'Paradesi',
       'Kaakkaa Muttai', 'Kayal', 'Pisasu', 'Lingaa', 'Kaaviya Thalaivan',
       'Kaththi', 'Jeeva', 'Madras',
       'Kathai Thiraikathai Vasanam Iyakkam', 'Jigarthanda',
       'Velaiilla Pattadhari', 'Sathuranga Vettai', 'Saivam',
       'Mundaasupatti', 'Kochadaiiyaan', 'Vaayai Moodi Pesavum', 'Cuckoo',
       'Thegidi', 'Pannaiyarum Padminiyum', 'Goli Soda', 'Veeram',
       'Visaaranai', 'Pasanga 2', 'Thoongaavanam', 'Naanum Rowdy Thaan',
       'Kuttram Kadithal', 'Kirumi', 'Maya', 'Thani Oruvan', 'Papanasam',
       'Indru Netru Naalai', 'Uttama Villain', 'OK Kanmani',
       'Rajathandhiram', 'Press 1 for Tamil',
       'Chennai 600028 Second Innings', 'Achcham Yenbadhu Madamaiyada',
       'Ammani', 'Kuttrame Thandanai', 'Dharmadurai', 'Metro', 'Iraivi',
       'Uriyadi', 'Oopiri', 'Kadhalum Kadanthu Pogum', 'Pichaikkaran',
       'Saala Khadoos', 'Crime 23', 'Muthuramalingam', 'Dream Factory',
       'Yaman', 'Ennodu Vilayadu', 'Kadhal Kan Kattudhe', 'Pagadi Aattam',
       'Rum', 'Singam 3', 'Bogan', 'Enakku Vaaitha Adimaigal',
       'Koditta Idangalai Nirappuga', 'Adhe Kangal', 'Bairavaa', 'Lens',
       'Aruvi', 'Ulkuththu', 'Balloon', 'Kalavaadiya Pozhuthugal',
       'Velaikkaran', 'Sakka Podu Podu Raja', 'Bhrama.com',
       'Chennai 2 Singapore', '12-12-1950', 'Kodiveeran', 'Richie',
       'Annadurai', 'Thiruttu Payale 2', 'English Padam', 'Indrajith',
       'En Aaloda Seruppa Kaanom', 'Theeran Adhigaram Ondru', 'C/o Surya',
       'Ippadai Vellum', 'Aramm', 'The House Next Door', 'Vizhithiru',
       'Kadaisi Bench Karthi', 'Meyaadha Maan', 'Solo',
       'Hara Hara Mahadevaki', 'Karuppan', 'Spyder', 'Bayama Irukku',
       'Aayirathil Iruvar', 'Kalavu Thozhirchalai', 'Veedevadu',
       'Thupparivaalan', 'Kathanayagan', 'Neruppu Da', 'Kurangu Bommai',
       'Maayavan', 'Puriyaatha Puthir', 'Thappu Thanda', 'Taramani',
       'Velaiyilla Pattathari 2', 'Podhuvaga En Manasu Thangam',
       'Kootathil Oruthan', 'Nibunan', 'Meesaya murukku', 'Rubaai',
       'Magalir Mattum', 'Pandigai', 'Thiri',
       'Gemini Ganesanum Suruli Rajanum', 'Chennaiyil Oru Naal 2',
       'Ivan Thanthiran', 'Adhagappattathu Magajanangalay',
       'Yaanum Theeyavan', 'Vanamagan',
       'Anbanavan Asaradhavan Adangadhavan', 'Maragatha Nananya', 'Uru',
       'Peechaankai', 'Rangoon', 'Sathriyan', 'Bongu',
       'Oru Kidayin Karunai Manu', 'Oru Iyakkunarin Kadhal Diary',
       '7 Naatkal', 'Thondan', 'Brindavanam', 'Inayathalam',
       'Sangili Bungili Kadhava Thorae', 'Yeidhavan',
       'Saravanan Irukka Bayamaen', 'Enga Amma Rani', 'Nagarvalam',
       'Sathya', 'Kadamban - Taqatwar', 'Sivalinga - Kanchana Returns',
       'Power Paandi', '8 Thottakkal', 'Kaatru Veliyidai', 'Dora',
       'Kavan', 'Kadugu', 'Paambhu Sattai', 'Dhayam', 'Vaigai Express',
       'Julieum 4 Perum', 'Bruce Lee', 'Kattappava Kanom',
       'Oru Mugathirai', 'Maanagaram', 'ACP Shiva', 'Mupparimanam',
       'Yaakkai', 'Peranbu', 'Maari 2', 'Adanga Maru', 'Kanaa',
       'Seethakaathi', 'Thuppakki Munai', 'Kaatrin Mozhi', 'Sarkar',
       'Pandem Kodi 2', 'Aan Devathai', 'Raatchasan', 'Nota', '96',
       'Pariyerum Perumal', 'Chekka Chivantha Vaanam', 'Raja Ranguski',
       'Saamy Square', 'U Turn', 'Seema Raja', 'Imaikkaa Nodigal',
       'Lakshmi', 'Odu Raja Odu', 'Kolamavu Kokila',
       'Pyaar Prema Kaadhal', 'Vishwaroopam 2', 'Ghajinikanth', 'Junga',
       'Mohini', 'Chinababu', 'Tamizh Padam 2.0', 'Goli Soda 2',
       'Iravukku Aayiram Kangal', 'Mahanati',
       'Iruttu Araiyil Murattu Kuthu', 'Karu', 'Mercury', 'Tik Tik Tik',
       '6 Athiyayam', 'Naachiyaar', 'Savarakathi', 'Kalakalappu 2',
       'Merku Thodarchi Malai', 'Bhaagamathie', 'Nimir',
       'Oru Nalla Naal Paathu Solren', 'Sketch', 'Enai Noki Paayum Thota',
       'Adithya Varma', 'Bigil', '100% Kadhal', 'Asuran', 'Kaappaan',
       'Magamuni', 'Saaho', 'Sixer', 'Bakrid', 'Kennedy Club', 'Comali',
       'Nerkonda Paarvai', 'Jackpot', 'A1', 'Aame', 'Kadaram Kondan',
       'Sivappu Manjal Pachai', 'Gurkha', 'Vennila Kabaddi Kuzhu 2',
       'Bodhai Yeri Budhi Maari', 'Kalavani 2', 'Raatchasi', 'Jiivi',
       'Dharma Prabhu', 'House Owner', 'Sindhubaadh', 'Thumbaa',
       'Game Over', 'Kolaigaran', 'NGK', 'Devi 2', 'Neeya 2', 'Ayogya',
       'Kee', 'K-13', 'Mr. Local', '100', 'Vellai Pookal',
       'Mehandi Circus', 'Kanchana 3', 'Watchman', 'Gangs Of Madras',
       'Uriyadi 2', 'Kuppathu Raja', 'Natpe Thunai', 'Super Deluxe',
       'Airaa', 'Agni Devi', 'Nedunalvaadai',
       'Ispade Rajavum Idhaya Raniyum', 'Sathru', 'Boomerang', 'Thadam',
       '90 ML', 'LKG', 'Vantha Rajavathaan Varuven', 'Dhilluku Dhuddu 2',
       'Dev', 'Charlie Chaplin 2', 'Master', 'Doctor', 'Karnan',
       'Sulthan', 'Maanaadu', 'Beast', 'Vikram', 'Thiruchitrambalam',
       'Ponniyin Selvan: I', 'Sardar', 'Annaatthe', 'Don', 'Jai Bhim',
       'Kaathuvaakula Rendu Kaadhal', 'Naane Varuvean', 'Enemy',
       'Navarasa', 'Pushpa: The Rise (Tamil Dub)', 'Valimai', 'Eeswaran',
       'Kabadadaari', 'Chakra', 'Kutty Story', 'Kalathil Santhippom',
       'Nenjam Marappathillai', 'Thaen', 'Kamali from Nadukkaveri',
       'Pogaru (Tamil Dub)', 'Bhoomi', 'Puli Joodham (Tamil Dub)',
       'Teddy', 'Calls', 'Pattas', 'MGR Magan', 'Kodiyil Oruvan',
       'Methagu', 'Thittam Irandu', 'Raangi',
       'Sivaranjiniyum Innum Sila Pengalum', 'Boomika', 'Thalaivii',
       'Aranmanai 3', 'Udanpirappe', 'Lift', 'Oh Manapenne', 'Mugizh',
       'Rudra Thandavam', 'Velan', 'Varudu Kaavalenu (Tamil Dub)',
       'Tughlaq Durbar', 'Cinderella', 'Chinnanjiru Kiliye', 'Netrikann',
       'Sarpatta Parambarai', 'Kasada Thapara', 'Boom Boom',
       'Sridevi Soda Center (Tamil Dub)', 'Thalli Pogathey', 'Maaran',
       'Idiot', 'Etharkkum Thunindhavan', 'Clap', 'Manmatha Leelai',
       'Hey Sinamika', 'Kaatteri', 'Selfie', 'Visithiran',
       'Kuttram Kuttrame', 'Ayngaran', 'O2', 'Veetla Vishesham', 'Yaanai',
       'Thummbad', 'Kallapart', 'Narkarappor', 'FIR', 'Yugi', 'D Block',
       'Diary', 'Rocketry: The Nambi Effect', 'Gatta Kusthi',
       'Pattathu Arasan', 'Naai Sekar',
       'Sila Nerangalil Sila Manithargal', 'Kombu Vatcha Singam',
       'Viruman', 'Jiivi 2', 'Kadaisi Vivasayi', 'Anbulla Ghilli',
       'Payanigal Gavanikkapadum', 'Sembi', 'Dejavu',
       'Kaarotiyin Kaadhali', 'Yaanai Mugathaan', 'Thaai Manasu',
       'Katteri', 'Kaalangalil Aval Vasantham', 'Methagu 2',
       'Thanne Vandi', 'Pothanur Thabal Nilayam', 'Adrishyam', 'Kanam',
       'Captain', 'Trigger', 'Natchathiram Nagargiradhu', 'Sinam',
       'Vendhu Thanindhathu Kaadu', 'Buffoon', 'Aadhaar', 'Rendagam',
       'Suzhal: The Vortex', 'Oke Oka Jeevitham (Tamil Dub)',
       'Krishna Vrinda Vihari (Tamil Dub)',
       'Dongalunnaru Jagratha (Tamil Dub)', 'Kaaneyadavum Kaattum',
       'Saani Kaayidham', 'Enna Solla Pogirai', 'Carbon', 'Theal',
       'Naai Sekar Returns', 'Mei Hoom Moosa (Tamil Dub)',
       'Enthada Saji (Tamil Dub)', 'Varisu', 'Thunivu', 'Jailer', 'Leo',
       'Ponniyin Selvan: II', 'Maaveeran', 'Jigarthanda DoubleX',
       'Por Thozhil', 'Chithha', 'Good Night', 'Viduthalai Part 1',
       'Irugapatru', 'Ayalaan', 'Mission: Chapter 1', 'Lover',
       'Aranmanai 4', 'Garudan', 'Maharaja', 'Raayan', 'Andhagan',
       'Demonte Colony 2', 'Vaazhai', 'The Greatest of All Time (GOAT)',
       'Lubber Pandhu', 'Amaran', 'Mark Antony', 'Chandramukhi 2',
       'Pathu Thala', 'Bagheera', 'Rudhran', 'Thiruvin Kural', 'Agilan',
       'Kannai Nambathey', 'Parundhaaguthu Oor Kuruvi',
       'Viduthalai Part 2', 'Dada', 'Bakkiyaraj',
       'Yaadhum Oore Yaavarum Kelir', 'Pichaikkaran 2', 'Tamilarasan',
       'Soppana Sundari', 'Good Luck Sakhi (Tamil Dub)', 'Bommai',
       'Run Baby Run', 'Thalaikoothal', 'Varayan', 'Ghosty',
       'Kondraal Paavam', 'Ariyavan', 'Naan Kadavul Illai', 'Thugs',
       'Single Shankarum Smartphone Simranum', 'Vasantha Mullai',
       'Annapoorani', 'Kalaga Thalaivan', 'Coffee with Kadhal',
       'Love Today', 'Prince', 'Nitham Oru Vaanam', 'Kaari', 'Web',
       'Murmur', 'Baby and Baby', 'Vaanil Thedinen', 'Pisasu 2',
       'Partner', 'Regina', 'Aneethi', 'Kick', 'Theera Kaadhal',
       'Marakkuma Nenjam', 'Karungaapiyam', 'Kazhuvethi Moorkkan',
       'Farhana', 'Erumbu', 'Burqa', 'Yaathisai', 'Asvins', 'Maamannan',
       'Bumper', 'Thandatti', 'D3', 'Deiva Machan', 'Kundakka Mandakka',
       'Pathirakaalam', 'Sathiya Sodhanai', 'Uruvam', 'Thuritham', 'Sync',
       'Raakayoor', 'Unnaal Ennaal', 'Malaikottai Vaaliban (Tamil Dub)',
       'Ayalvaasi', 'Kida', 'Modern Love Chennai', 'Pareshan (Tamil Dub)',
       'Rayar Parambarai', 'Let’s Get Married', 'Parking',
       'Annapurna Photo Studio (Tamil Dub)', 'Chennai Story',
       '80s Buildup', 'Conjuring Kannappan',
       'Journey of Love 18+ (Tamil Dub)', 'Shot Boot Three',
       'Vivekanandan Viralaanu (Tamil Dub)', 'Ape School',
       'Vithaikkaaran', 'Operation Valentine (Tamil Dub)',
       'Ambajipeta Marriage Band (Tamil Dub)', 'Eagle (Tamil Dub)',
       'Lal Salaam', 'Siren', 'Madame Web (Tamil Dub)', 'Blue Star',
       'Singapore Saloon', 'Thookudurai', 'Khichdi 2 (Tamil Dub)', 'Jama',
       'Vadakkupatti Ramasamy', 'Byri', 'Merry Christmas',
       'Lucky Baskhar', 'Mission', 'Pogum',
       'Kishkindha Kaandam (Tamil Dub)', 'Satyam Sundaram (Tamil Dub)',
       'Anandhapuram Diaries (Tamil Dub)', 'Mathimaran', 'Athomugam',
       'Chennai City Gangsters', 'Idiyappam', 'Por', 'Aalakaalam',
       'Thalaimai Seyalagam', 'Kottukkaali', 'Nandhan', 'Black',
       'Raghu Thatha', 'Kadaisi Ulaga Por', 'Meiyazhagan', 'Petta Rap',
       'Hindustani 2', 'Pavithra 1994', 'Vettaiyan', 'Kanguva',
       'Indian 2', 'Thangalaan', 'Boat', 'Democracy', 'Oru Nodi',
       'Good Bad Ugly', 'Retro', 'Vidaamuyarchi', 'Thug Life',
       'Kadhalikka Neramillai', 'Vanangaan', 'Madha Gaja Raja',
       'Veera Dheera Sooran: Part 2', 'Kubera', 'Dragon', 'Ace',
       'Maargan', 'Sabdham', 'Nilavuku Enmel Ennadi Kobam',
       'Ramam Raghavam', 'Fire 2025', 'Oho Enthan Baby', 'Desingu Raja 2',
       'Mrs and Mr', 'Maayakoothu', 'Thottram', 'Superman (Tamil Dub)',
       'Game Changer (Tamil Dub)', 'Madraskaaran', 'Nesippaya',
       'Tharunam', 'Good Day', 'Phoenix', 'Paranthu Po', 'DNA',
       'Aghathiyaa', 'Train', 'Idly Kadai', 'Paarasiga Raja',
       'Bun Butter Jam', 'Yaadhum Ariyaan', 'Achamillai Achamillai',
       'Seetha Payana', 'The Verdict', 'Tourist Family', 'DD Next Level',
       'Gangers', 'Bottle Radha', 'MGR Magan 2', 'Vaa Vaathiyaar',
       'Empuraan (Tamil Dub)', 'SK23', 'Suriya 44', 'Sardar 2',
       'Thalapathy 69', 'Coolie', 'Maaya One (Tamil Dub)', 'Freedom',
       'Mr Zoo Keeper', 'Narivetta', 'Paramasivan Fathima', 'Gajarama',
       'Jagamerigina Satyam', 'Thamizh Desam', 'Kaatu Pura',
       'Pudhusa Naan Poranthen', 'Vetri Vizha 2', 'Anbulla Appa',
       'Kanne Kalaimaane 2', 'Naanum Rowdy Dhaan 2', 'Pudhupettai 2',
       'Sivaji 3D (Re-release)', 'Thoothukudi Thalapathy',
       'Kuttram 23 Part 2', 'Ennai Vittu Pogaathe', 'Pisasu 3',
       'Kaadhal Konjam', 'Thiruma', 'Vaadi Vaasal', 'Aaranya Kaandam 2',
       'Karthikeyan', 'Oru Kalluriyin Kadhai', 'Mouna Raagam 2',
       'Thalaimai Seyalagam 2', 'Raaja Paarvai', 'Koodal Nagar',
       'Naan Rudhran', 'Thoongavanam 2'], dtype=object)

In [ ]:
import pickle as pkl

In [ ]:
pkl.dump(df,open('df.pkl','wb'))

In [ ]:
pkl.dump(df,open('cosine.pkl','wb'))